In [1]:
import pandas as pd
import numpy as np
import plotly.express as px

sales = pd.read_csv("/Users/jordan.arlan/Documents/DS100/Data/vgsales.csv")
sales

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

In [2]:
sales[["Year", "NA_Sales", "EU_Sales", "JP_Sales", "Other_Sales", "Global_Sales"]].groupby("Year").agg(sum)

        NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales
Year
1980.0     10.59      0.67      0.00         0.12         11.38
1981.0     33.40      1.96      0.00         0.32         35.77
1982.0     26.92      1.65      0.00         0.31         28.86
1983.0      7.76      0.80      8.10         0.14         16.79
1984.0     33.28      2.10     14.27         0.70         50.36
1985.0     33.73      4.74     14.56         0.92         53.94
1986.0     12.50      2.84     19.81         1.93         37.07
1987.0      8.46      1.41     11.63         0.20         21.74
1988.0     23.87      6.59     15.76         0.99         47.22
1989.0     45.15      8.44     18.36         1.50         73.45
1990.0     25.46      7.63     14.88         1.40         49.39
1991.0     12.76      3.95     14.78         0.74         32.23
1992.0     33.87     11.71     28.91         1.65         76.16
1993.0     15.12      4.65     25.33         0.89         45.98
1994.0     28.15     14.88     33.99         2.20         79.17
1995.0     24.82     14.90     45.75         2.64         88.11
1996.0     86.76     47.26     57.44         7.69        199.15
1997.0     94.75     48.32     48.87         9.13        200.98
1998.0    128.36     66.90     50.04        11.03        256.47
1999.0    126.06     62.67     52.34        10.05        251.27
2000.0     94.49     52.75     42.77        11.62        201.56
2001.0    173.98     94.89     39.86        22.76        331.47
2002.0    216.19    109.74     41.76        27.28        395.52
2003.0    193.59    103.81     34.20        26.01        357.85
2004.0    222.59    107.32     41.65        47.29        419.31
2005.0    242.61    121.94     54.28        40.58        459.94
2006.0    263.12    129.24     73.73        54.43        521.04
2007.0    312.05    160.50     60.29        77.60        611.13
2008.0    351.44    184.40     60.26        82.39        678.90
2009.0    338.85    191.59     61.89        74.77        667.30
2010.0    304.24    176.73     59.49        59.90        600.45
2011.0    241.06    167.44     53.04        54.39        515.99
2012.0    154.96    118.78     51.74        37.82        363.54
2013.0    154.77    125.80     47.59        39.82        368.11
2014.0    131.97    125.65     39.46        40.02        337.05
2015.0    102.82     97.71     33.72        30.01        264.44
2016.0     22.66     26.76     13.70         7.75         70.93
2017.0      0.00      0.00      0.05         0.00          0.05
2020.0      0.27      0.00      0.00         0.02          0.29

In [3]:
sales_list = ["NA_Sales", "EU_Sales", "JP_Sales", "Other_Sales", "Global_Sales"]
sales[["Genre", "NA_Sales", "EU_Sales", "JP_Sales", "Other_Sales", "Global_Sales"]].groupby("Genre").agg(sum)

              NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales
Genre
Action          877.83    525.00    159.95       187.38       1751.18
Adventure       105.80     64.13     52.07        16.81        239.04
Fighting        223.59    101.32     87.35        36.68        448.91
Misc            410.24    215.98    107.76        75.32        809.96
Platform        447.05    201.63    130.77        51.59        831.37
Puzzle          123.78     50.78     57.31        12.55        244.95
Racing          359.42    238.39     56.69        77.27        732.04
Role-Playing    327.28    188.06    352.31        59.61        927.37
Shooter         582.60    313.27     38.28       102.69       1037.37
Simulation      183.31    113.38     63.70        31.52        392.20
Sports          683.35    376.85    135.37       134.97       1330.93
Strategy         68.70     45.34     49.46        11.36        175.12

In [4]:
sales.sort_values("Global_Sales", ascending=False).groupby("Platform").agg(lambda x : x.iloc[0]).sort_values("Year")

,Rank,Name,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
Platform,,,,,,,,,,
2600,90,Pac-Man,1982.0,Puzzle,Atari,7.28,0.45,0.00,0.08,7.81
NES,2,Super Mario Bros.,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
SNES,19,Super Mario World,1990.0,Platform,Nintendo,12.78,3.75,3.54,0.55,20.61
GEN,144,Sonic the Hedgehog 2,1992.0,Platform,Sega,4.47,1.20,0.16,0.19,6.03
GG,13527,Sonic the Hedgehog 2 (8-bit),1992.0,Platform,Sega,0.00,0.00,0.04,0.00,0.04
SCD,1263,Sonic CD,1993.0,Platform,Sega,1.00,0.36,0.09,0.05,1.50
NG,6683,Samurai Shodown II,1994.0,Fighting,SNK,0.00,0.00,0.25,0.00,0.25
3DO,12637,Policenauts,1995.0,Adventure,Konami Digital Entertainment,0.00,0.00,0.06,0.00,0.06
TG16,9225,Doukyuusei,1995.0,Adventure,NEC,0.00,0.00,0.14,0.00,0.14
SAT,890,Virtua Fighter 2,1995.0,Fighting,Sega,0.34,0.26,1.30,0.03,1.93
GB,5,Pokemon Red/Pokemon Blue,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
PCFX,14559,Blue Breaker: Ken Yorimo Hohoemi o,1996.0,Role-Playing,NEC,0.00,0.00,0.03,0.00,0.03
N64,47,Super Mario 64,1996.0,Platform,Nintendo,6.91,2.85,1.91,0.23,11.89
PS,53,Gran Turismo,1997.0,Racing,Sony Computer Entertainment,4.02,3.87,2.54,0.52,10.95
DC,638,Sonic Adventure,1998.0,Platform,Sega,1.26,0.61,0.46,0.08,2.42
WS,3933,Final Fantasy,2000.0,Role-Playing,SquareSoft,0.00,0.00,0.51,0.00,0.51
GC,108,Super Smash Bros. Melee,2001.0,Fighting,Nintendo,4.41,1.04,1.39,0.22,7.07
GBA,26,Pokemon Ruby/Pokemon Sapphire,2002.0,Role-Playing,Nintendo,6.06,3.90,5.38,0.50,15.85
XB,80,Halo 2,2004.0,Shooter,Microsoft Game Studios,6.82,1.53,0.05,0.08,8.49
PS2,18,Grand Theft Auto: San Andreas,2004.0,Action,Take-Two Interactive,9.43,0.40,0.41,10.57,20.81
PSP,91,Grand Theft Auto: Liberty City Stories,2005.0,Action,Take-Two Interactive,2.90,2.83,0.24,1.75,7.72
Wii,1,Wii Sports,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
DS,7,New Super Mario Bros.,2006.0,Platform,Nintendo,11.38,9.23,6.50,2.90,30.01
PC,84,The Sims 3,2009.0,Simulation,Electronic Arts,0.98,6.42,0.00,0.71,8.11
X360,16,Kinect Adventures!,2010.0,Misc,Microsoft Game Studios,14.97,4.94,0.24,1.67,21.82
3DS,33,Pokemon X/Pokemon Y,2013.0,Role-Playing,Nintendo,5.17,4.05,4.34,0.79,14.35
PS3,17,Grand Theft Auto V,2013.0,Action,Take-Two Interactive,7.01,9.27,0.97,4.14,21.40
PSV,715,Minecraft,2014.0,Misc,Sony Computer Entertainment Europe,0.28,0.79,0.87,0.32,2.25
WiiU,109,Mario Kart 8,2014.0,Racing,Nintendo,3.13,2.07,1.27,0.49,6.96
PS4,34,Call of Duty: Black Ops 3,2015.0,Shooter,Activision,5.77,5.81,0.35,2.31,14.24
XOne,102,Call of Duty: Black Ops 3,2015.0,Shooter,Activision,4.52,2.09,0.01,0.67,7.30

In [5]:
sales.groupby("Year").size()

Year
1980.0       9
1981.0      46
1982.0      36
1983.0      17
1984.0      14
1985.0      14
1986.0      21
1987.0      16
1988.0      15
1989.0      17
1990.0      16
1991.0      41
1992.0      43
1993.0      60
1994.0     121
1995.0     219
1996.0     263
1997.0     289
1998.0     379
1999.0     338
2000.0     349
2001.0     482
2002.0     829
2003.0     775
2004.0     763
2005.0     941
2006.0    1008
2007.0    1202
2008.0    1428
2009.0    1431
2010.0    1259
2011.0    1139
2012.0     657
2013.0     546
2014.0     582
2015.0     614
2016.0     344
2017.0       3
2020.0       1
dtype: int64

In [6]:
sales.groupby("Year").filter(lambda sf: sf["Global_Sales"].max() < 5)

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
221,222,FIFA 17,PS4,2016.0,Sports,Electronic Arts,0.28,3.75,0.06,0.69,4.77
231,232,The Legend of Zelda: A Link to the Past,SNES,1991.0,Action,Nintendo,2.42,0.91,1.15,0.13,4.61
239,240,Pitfall!,2600,1981.0,Platform,Activision,4.21,0.24,0.00,0.05,4.50
251,252,Zelda II: The Adventure of Link,NES,1987.0,Adventure,Nintendo,2.19,0.50,1.61,0.08,4.38
254,255,Sonic the Hedgehog,GEN,1991.0,Platform,Sega,3.03,0.91,0.26,0.13,4.34
...,...,...,...,...,...,...,...,...,...,...,...
16562,16565,Mighty No. 9,XOne,2016.0,Platform,Deep Silver,0.01,0.00,0.00,0.00,0.01
16569,16572,Resident Evil 4 HD,XOne,2016.0,Shooter,Capcom,0.01,0.00,0.00,0.00,0.01
16570,16573,Farming 2017 - The Simulation,PS4,2016.0,Simulation,UIG Entertainment,0.00,0.01,0.00,0.00,0.01
16576,16579,Rugby Challenge 3,XOne,2016.0,Sports,Alternative Software,0.00,0.01,0.00,0.00,0.01
16589,16592,Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...,PSV,2016.0,Action,dramatic create,0.00,0.00,0.01,0.00,0.01

In [7]:
# Find the total global sales each year for each platform
sales.groupby(["Year", "Platform"])[sales_list].agg(sum)

                 NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales
Year   Platform
1980.0 2600         10.59      0.67      0.00         0.12         11.38
1981.0 2600         33.40      1.96      0.00         0.32         35.77
1982.0 2600         26.92      1.65      0.00         0.31         28.86
1983.0 2600          5.44      0.34      0.00         0.06          5.83
       NES           2.32      0.46      8.10         0.08         10.96
...                   ...       ...       ...          ...           ...
2016.0 X360          0.36      0.40      0.00         0.07          0.83
       XOne          6.69      4.63      0.01         1.05         12.37
2017.0 PS4           0.00      0.00      0.03         0.00          0.03
       PSV           0.00      0.00      0.02         0.00          0.02
2020.0 DS            0.27      0.00      0.00         0.02          0.29

[241 rows x 5 columns]

In [8]:
# The `pivot_table` method is used to generate a Pandas pivot table
import numpy as np
sales.pivot_table(index = "Year", columns = "Platform", values = "Global_Sales", aggfunc = np.sum)

Platform,2600,3DO,3DS,DC,DS,GB,GBA,GC,GEN,GG,...,SAT,SCD,SNES,TG16,WS,Wii,WiiU,X360,XB,XOne
Year,,,,,,,,,,,,,,,,,,,,,
1980.0,11.38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1981.0,35.77,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1982.0,28.86,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1983.0,5.83,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1984.0,0.27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1985.0,0.45,NaN,NaN,NaN,0.02,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1986.0,0.66,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1987.0,1.98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1988.0,0.75,NaN,NaN,NaN,NaN,1.43,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1989.0,0.62,NaN,NaN,NaN,NaN,64.98,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990.0,NaN,NaN,NaN,NaN,NaN,4.89,NaN,NaN,2.60,NaN,...,NaN,NaN,26.16,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991.0,NaN,NaN,NaN,NaN,NaN,5.57,NaN,NaN,4.34,NaN,...,NaN,NaN,16.21,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1992.0,NaN,NaN,NaN,NaN,NaN,25.48,NaN,NaN,12.66,0.04,...,NaN,NaN,32.98,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1993.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.65,NaN,...,NaN,1.50,40.01,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1994.0,NaN,0.02,NaN,NaN,NaN,12.17,NaN,NaN,8.11,NaN,...,3.64,0.37,35.08,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1995.0,NaN,0.08,NaN,NaN,NaN,3.60,NaN,NaN,NaN,NaN,...,11.58,NaN,32.21,0.16,NaN,NaN,NaN,NaN,NaN,NaN
1996.0,NaN,NaN,NaN,NaN,NaN,36.02,NaN,NaN,NaN,NaN,...,7.69,NaN,15.93,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1997.0,NaN,NaN,NaN,NaN,NaN,6.37,NaN,NaN,NaN,NaN,...,6.77,NaN,0.99,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1998.0,NaN,NaN,NaN,3.39,NaN,26.90,NaN,NaN,NaN,NaN,...,3.82,NaN,0.22,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1999.0,NaN,NaN,NaN,5.17,NaN,38.01,NaN,NaN,NaN,NaN,...,0.09,NaN,0.26,NaN,0.46,NaN,NaN,NaN,NaN,NaN
2000.0,NaN,NaN,NaN,5.99,NaN,19.76,0.06,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.68,NaN,NaN,NaN,0.99,NaN
2001.0,NaN,NaN,NaN,1.07,NaN,9.24,61.62,26.30,NaN,NaN,...,NaN,NaN,NaN,NaN,0.28,NaN,NaN,NaN,22.24,NaN
2002.0,NaN,NaN,NaN,0.29,NaN,NaN,74.38,51.93,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48.15,NaN
2003.0,NaN,NaN,NaN,NaN,NaN,NaN,56.73,50.66,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,55.16,NaN
2004.0,NaN,NaN,NaN,NaN,17.46,NaN,78.09,28.89,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65.50,NaN
2005.0,NaN,NaN,NaN,NaN,131.40,NaN,33.90,27.80,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.32,49.17,NaN
2006.0,NaN,NaN,NaN,NaN,121.15,NaN,5.35,11.29,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,137.91,NaN,51.88,10.15,NaN
2007.0,NaN,NaN,NaN,0.02,149.36,NaN,3.43,0.27,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,154.97,NaN,95.84,0.55,NaN
2008.0,NaN,NaN,NaN,0.04,147.89,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,174.16,NaN,135.76,0.18,NaN
2009.0,NaN,NaN,NaN,NaN,121.99,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,210.44,NaN,120.85,NaN,NaN
2010.0,NaN,NaN,NaN,NaN,87.98,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,131.80,NaN,171.05,NaN,NaN
2011.0,NaN,NaN,62.53,NaN,27.80,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,62.41,NaN,145.12,NaN,NaN
2012.0,NaN,NaN,51.14,NaN,11.64,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,22.77,17.84,100.88,NaN,NaN
2013.0,NaN,NaN,55.88,NaN,1.96,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,9.36,21.84,89.61,NaN,18.60
2014.0,NaN,NaN,43.14,NaN,0.02,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,4.44,22.51,36.42,NaN,52.43
2015.0,NaN,NaN,26.99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.55,16.38,13.05,NaN,57.66
2016.0,NaN,NaN,6.60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,3.29,0.83,NaN,12.37
2017.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020.0,NaN,NaN,NaN,NaN,0.29,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
l = sales[["Name","Platform", "Global_Sales"]]
r = sales[["Name", "Platform" ,"Other_Sales"]]

In [10]:
m = pd.merge(left = l, right = r, left_on = ["Name","Platform"], right_on = ["Name","Platform"])
m

,Name,Platform,Global_Sales,Other_Sales
0,Wii Sports,Wii,82.74,8.46
1,Super Mario Bros.,NES,40.24,0.77
2,Mario Kart Wii,Wii,35.82,3.31
3,Wii Sports Resort,Wii,33.00,2.96
4,Pokemon Red/Pokemon Blue,GB,31.37,1.00
...,...,...,...,...
16603,Woody Woodpecker in Crazy Castle 5,GBA,0.01,0.00
16604,Men in Black II: Alien Escape,GC,0.01,0.00
16605,SCORE International Baja 1000: The Official Game,PS2,0.01,0.00
16606,Know How 2,DS,0.01,0.00
16607,Spirits & Spells,GBA,0.01,0.00